export enum StorageItem {
  USER = 'CBBG__USER',
  ACCESS_TOKEN = 'CBBG__ACCESS_TOKEN',
  ID_TOKEN = 'CBBG__ID_TOKEN',
  REDIRECT_TO_AFTER = 'CBBG__REDIRECT_TO_AFTER',
  BROWSER_TABS_COUNT = 'CBBG__BROWSER_TABS_COUNT',
  BROWSER_STORAGE_TIME = 'CBBG__BROWSER_STORAGE_TIME',
  BROWSER_CLOSED = 'CBBG__BROWSER_CLOSED',
}
